### ISSUE TITLE
Plugin removes additional permissions provided in default role

### ISSUE THREAD

**Issue by jospas** [shelfio/serverless-simplify-default-exec-role-plugin#2]
Hi there,

Just testing this out on a larger project that I was creating a custom IAM role and policies and then attaching to Lambda functions.

I moved to an IAM role definition in the provider per recommendations and hit the policy size exceeded issue.

I tried your plugin but all other required role statements are now stripped out.

Could you perhaps be less aggressive in simplifying the log stream statements or suggest a way I can add additional statements to the default role?

**Comment by jospas** [comment]
Never mind I went back to custom roles as I need fine grained control, thank you for the ideas in this though very tidy plugin

**Comment by nykolaslima** [comment]
@vladgolubev any way to get it working without lossing default roles?
