### ISSUE TITLE
Incorrect Plugin Import Instructions

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [shelfio/serverless-simplify-default-exec-role-plugin#3]
Thanks for this package, works great!

Just 1 update required for readme, we ran into an issue where it couldn't find your package after installing it. You need to add the `@shelf/` prefix to the plugin name.

your instructions say:
```yaml
plugins:
  - serverless-simplify-default-exec-role-plugin
```

should be:
```yaml
plugins:
  - '@shelf/serverless-simplify-default-exec-role-plugin'
```

**Comment by vladholubiev** [comment]
Thanks!!

Updated:

<img width="597" alt="2022-08-29T20 12 29-idJGZtvt" src="https://user-images.githubusercontent.com/3817380/187269747-7292096d-79b4-4635-9351-d8ebb96dde62.png">
